name: cucumia_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  syncfusion_flutter_charts: ^19.4.47
  syncfusion_flutter_datepicker: ^19.4.48
  enum_to_string: ^2.0.1
  bot_toast: ^4.0.1
  shimmer: ^2.0.0
  dropdown_button2: ^1.1.1
  badges: ^2.0.2
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.0
  image_stack: ^2.1.0
  package_info_plus: ^1.3.0

  graphql: ^5.0.1-beta.5
  graphql_flutter: ^5.0.1-beta.5
  hive_flutter: ^1.1.0
  hive: ^2.0.5
  amplify_datastore_plugin_interface: ^0.2.10

  url_strategy: ^0.2.0
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter_iconly: ^1.0.2
  iconly: ^1.0.1
  get: 4.6.1
  flutter_dashboard:
    path: ./plugins/flutter_dashboard
  flutter:
    sdk: flutter
  keyboard_dismisser: ^2.0.0
  file_picker: ^4.3.3
  csv: ^5.0.1
  dependencies:
  number_pagination: ^0.0.3+2  
  toggle_switch: ^1.4.0
  firebase_storage: ^10.2.7
  mime_type: ^1.0.0
  amplify_api: ^0.2.10
  amplify_flutter: ^0.2.10
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.20
  uuid: ^3.0.6


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
